name: edu
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0  # Ensure this matches the latest stable version


  firebase_core: ^2.24.0  # Latest version as of June 2025
  firebase_auth: ^4.16.0  # Latest version
  cloud_firestore: ^4.13.0  # Latest version
  google_sign_in: ^6.1.0  # Latest version
  shared_preferences: ^2.2.0  # For language persistence
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/  # Updated to match the directory structure, no trailing slash

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf  # Updated path to match subdirectory
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto_Condensed-Regular.ttf  # Add this font file if missing
